name: blog
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=2.1.4
  - numpy=1.26.2
  - requests=2.31.0
  - selenium=4.16.0
  - beautifulsoup4=4.12.2
  - python-dotenv=1.0.0
  - pyyaml=6.0.1
  - pip=23.3.1
  - pip:
    - yfinance==0.2.36
    - pandas-datareader==0.10.0
    - webdriver-manager==4.0.1
    - schedule==1.2.1
